### ISSUE TITLE
Keep Image resolution (DPI)

### ISSUE THREAD

**Issue by tuananhcmc** [victordomingos/optimize-images#23] opened 2020-05-30 04:21 UTC
After compressing, the resolution goes down - in my case from 300 to 72 (DPI) . Can you please allow an option for keeping the image resolution the same

**Comment by victordomingos** [comment] 2020-05-30 10:07
Hi! Thank you very much for reporting this issue.

In order to be able to investigate it, we need some additional details on your setup, the images and the end result:

- Which version of Optimize Images are you using (e.g, current GitHub master, latest pip,...)?

- Which versions of Python and Pillow were you using?

- What command-line arguments did you pass to Optimize Images?

- Can you please provide a sample set of images for further inspection (for instance, one original image and the result optimized file)?

**Comment by victordomingos** [comment] 2020-05-30 20:35
You could also check if using `-ke`/`--keep-exif` as a command-line argument solves the issue for you. If so, it’s the intended behavior. The default parameters are meant to optimize for web, a use case where DPI indication does not matter as much as the image dimensions.

**Comment by victordomingos** [comment] 2020-06-07 23:16
After some testing using `-ke`/`--keep-exif`, it seems that image resolution information (DPI) is being correctly saved, so I am closing this issue for now. Please feel free to reopen it in case you have further related issues.

**Closed as completed by victordomingos** 2020-06-07 23:16 UTC
